modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Adds thirst compatibility for drinks.'''

[[dependencies.fillthirst]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.fillthirst]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.fillthirst]]
modId="thirst"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="youkaishomecoming"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="kaleidoscope_tavern"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="kaleidoscope_cookery"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="kaleidoscope_dim_wine"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="extradelight"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="fruitsdelight"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="hearthandharvest"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="culturaldelights"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="eternal_starlight_delight"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="mynethersdelight"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="ubesdelight"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="miners_delight"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.fillthirst]]
modId="crabbersdelight"
type="optional"
ordering="AFTER"
side="BOTH"
